# Generated by Django 3.2.13 on 2023-04-14 07:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='like_users',
            field=models.ManyToManyField(default=0, related_name='like_movies', to=settings.AUTH_USER_MODEL),
        ),
    ]
